name: Deptry
on: [push]

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python "3.12"
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      #----------------------------------------------
      # Run deptry
      #----------------------------------------------
      - name: Deptry
        run: poetry run deptry .
